services:
  app:
    build: ./
    restart: always
    secrets:
      - db-password
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=cache
      - TZ=Asia/Shanghai
    networks:
      - app
    ports:
      - 8080:8080
      - 18080:18080
      - 1099:1099
    volumes:
      - app-log:/workdir/logs
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
  db:
    build: ./db
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    networks:
      - app
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - TZ=Asia/Shanghai
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 40s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
  cache:
    restart: always
    image: redis:6.2
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app
    volumes:
      - ./cache:/usr/local/etc/redis
      - cache-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    
volumes:
  db-data: {}
  app-log: {}
  cache-data: {}
secrets:
  db-password:
    file: db/password.txt
networks:
  app: {}