management:
  server:
    port: 18080
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
    enabled-by-default: true
server:
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: true
  tomcat:
    mbeanregistry:
      enabled: true
    accesslog:
      enabled: true
spring:
  jmx:
    enabled: true
    default-domain:
  application:
    name: @artifactId@
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 3
            threadPriority: 2
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            misfireThreshold: 60000
            useProperties: false # true时JobDataMap的value只能是String类型
            isClustered: true
            dataSource: QuartzDS
          dataSource:
            QuartzDS:
              driver: ${spring.datasource.driver-class-name}
              user: ${spring.datasource.username}
              password: ${spring.datasource.password}
              URL: jdbc:mysql://127.0.0.1:3306/quartz?useUnicode=true&useSSL=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
              validationQuery: select 0 from dual
          scheduler:
            instanceId: AUTO
    scheduler-name: "MyScheduler"
    job-store-type: "jdbc"
  cache:
    type: REDIS
    redis:
      time-to-live: 15m
      cache-null-values: false
      enable-statistics: true
      key-prefix: 'cache:${spring.application.name}:'
  devtools:
    restart:
      enabled: true
  graphql:
    websocket:
      path: /graphql
    graphiql:
      enabled: true
    schema:
      file-extensions:
        - .graphql
        - .graphqls
        - .gqls
      printer:
        enabled: true
    cors:
      allowed-methods: POST
      allowed-headers: '*'
      allowed-origins: '*'
  redis:
    database: 0
    host: 127.0.0.1
    password: yx123123=
    client-type: lettuce
    lettuce:
      pool:
        max-wait: 10s
        min-idle: 4
        time-between-eviction-runs: 10s
        enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aus-call-center?useUnicode=true&useSSL=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: shanglian123
    hikari:
      # 默认值30秒
      connectionTimeout: 1000
      validationTimeout: 1000
      idleTimeout: 30000
      maxLifetime: 60000
      maximumPoolSize: 5
      minimumIdle: 3
      poolName: "mysql-auscallcenter-pool"
      loggingMeterPushMetricsStep: 15
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
logging:
  config: classpath:logback-spring.xml
  level:
    reactor:
      netty: debug
    notprivacysafe: INFO
    org:
      springframework:
        web: debug
        http: debug
        graphql: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    cache-enabled: true
    localCacheScope: STATEMENT
    map-underscore-to-camel-case: true
---
server:
  tomcat:
    accesslog:
      directory: /var/logs/tomcat
spring:
  profiles: prod
  devtools:
    restart:
      enabled: false
  graphql:
    graphiql:
      enabled: false
  quartz:
    properties:
      org:
        quartz:
          dataSource:
            QuartzDS:
              URL: jdbc:mysql://${MYSQL_HOST:db}:3306/quartz?useUnicode=true&useSSL=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
  redis:
    password:
    host: ${REDIS_HOST:cache}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:db}:3306/aus-call-center?useUnicode=true&useSSL=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    password: ${MYSQL_PASSWORD:shanglian123}
log-home: /var/logs/${spring.application.name}
logging:
  level:
    reactor:
      netty: INFO
    notprivacysafe: INFO
    org:
      springframework:
        web: INFO
        http: INFO
        graphql: INFO
---
server:
  tomcat:
    accesslog:
      directory: /Volumes/k1/logs/tomcat
spring:
  profiles: mac
log-home: /Volumes/k1/logs/${spring.application.name}

---
server:
  tomcat:
    accesslog:
      directory: D:/logs/undertow
spring:
  profiles: win
log-home: D:/logs/${spring.application.name}